# Generated by Django 5.1 on 2024-08-12 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sample_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
