# Generated by Django 5.1 on 2024-08-12 19:34

import samples.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_sample_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='unique_id',
            field=models.PositiveIntegerField(default=samples.models.generate_unique_id, unique=True),
        ),
    ]
