# Generated by Django 5.1 on 2024-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_alter_sample_id_alter_sample_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='audit',
            field=models.BooleanField(default=False),
        ),
    ]
