# Generated by Django 5.1.1 on 2025-09-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='sharepoint_folder_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
