# Generated by Django 5.1.1 on 2024-11-27 13:49

import django.db.models.deletion
import samples.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_sample_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='storage_location',
            field=models.CharField(blank=True, choices=[('Test Lab Fridge', 'Test Lab Fridge'), ('Test Lab Freezer', 'Test Lab Freezer'), ('Walk-in Fridge', 'Walk-in Fridge'), ('Walk-in Freezer', 'Walk-in Freezer'), ('Dry Food Storage', 'Dry Food Storage'), ('Empty Case Storage', 'Empty Case Storage')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='unique_id',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=samples.models.CustomFileSystemStorage(), upload_to=samples.models.get_image_upload_path)),
                ('full_size_image', models.ImageField(blank=True, null=True, storage=samples.models.FullSizeImageStorage(), upload_to=samples.models.get_full_size_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='samples.sample')),
            ],
        ),
    ]
