# Generated by Django 5.1.1 on 2024-11-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_alter_sample_storage_location_alter_sample_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleimage',
            name='full_size_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
