# Generated by Django 5.1.1 on 2024-12-04 14:09

import samples.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_alter_sampleimage_full_size_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleimage',
            name='full_size_image',
            field=models.ImageField(blank=True, null=True, storage=samples.models.FullSizeImageStorage(), upload_to=samples.models.get_full_size_image_upload_path),
        ),
    ]
