# Generated by Django 5.1.1 on 2025-01-16 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.opportunity'),
        ),
    ]
