# Generated by Django 5.1.1 on 2025-01-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_sample_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='opportunity',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
