# Generated by Django 5.1.1 on 2025-01-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_remove_sample_opportunity_delete_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_number', models.CharField(max_length=255, unique=True)),
                ('new', models.BooleanField(default=False)),
            ],
        ),
    ]
