# Generated by Django 5.1.1 on 2025-01-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='sample_ids',
            field=models.TextField(blank=True),
        ),
    ]
