# Generated by Django 5.1.1 on 2025-01-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_opportunity_sample_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='update',
            field=models.BooleanField(default=True),
        ),
    ]
