# Generated by Django 5.1.1 on 2025-01-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_opportunity_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='rsm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
