# Generated by Django 5.1.1 on 2025-02-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_opportunity_customer_opportunity_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='apps_eng',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
