# Generated by Django 5.1.1 on 2025-02-11 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0016_sample_apps_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleimage',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='samples.sample'),
        ),
    ]
