# Generated by Django 5.1.1 on 2025-03-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0017_alter_sampleimage_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='sample_info_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
