# Generated by Django 5.1.1 on 2025-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0018_opportunity_sample_info_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='sample_info_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
