# Generated by Django 5.1.1 on 2025-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0019_opportunity_sample_info_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='audit_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='last_audit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='location_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
