# Generated by Django 5.1.1 on 2025-09-02 13:19

from django.db import migrations


def update_storage_locations(apps, schema_editor):
    Sample = apps.get_model('samples', 'Sample')
    
    # Update all samples with old location names to new ones
    Sample.objects.filter(storage_location="Test Lab Fridge").update(storage_location="Cooler #2")
    Sample.objects.filter(storage_location="Test Lab Freezer").update(storage_location="Freezer #5")


def reverse_storage_locations(apps, schema_editor):
    Sample = apps.get_model('samples', 'Sample')
    
    # Reverse the updates (for migration rollback)
    Sample.objects.filter(storage_location="Cooler #2").update(storage_location="Test Lab Fridge")
    Sample.objects.filter(storage_location="Freezer #5").update(storage_location="Test Lab Freezer")


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0021_set_initial_audit_dates'),
    ]

    operations = [
        migrations.RunPython(update_storage_locations, reverse_storage_locations),
    ]
