# Generated by Django 5.1.1 on 2025-09-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0022_update_storage_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='storage_location',
            field=models.CharField(blank=True, choices=[('Cooler #2', 'Cooler #2'), ('Freezer #5', 'Freezer #5'), ('Freezer #9', 'Freezer #9'), ('Walk-in Fridge', 'Walk-in Fridge'), ('Walk-in Freezer', 'Walk-in Freezer'), ('Dry Food Storage', 'Dry Food Storage'), ('Empty Case Storage', 'Empty Case Storage')], max_length=255, null=True),
        ),
    ]
