# Generated by Django 5.1.1 on 2025-09-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0023_sample_created_at_sample_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('SAMPLE_CREATE', 'Sample Created'), ('SAMPLE_UPDATE', 'Sample Updated'), ('SAMPLE_DELETE', 'Sample Deleted'), ('SAMPLE_REMOVE', 'Sample Removed from Inventory'), ('SAMPLE_AUDIT', 'Sample Audited'), ('LOCATION_CHANGE', 'Location Changed'), ('BULK_AUDIT', 'Bulk Audit'), ('BULK_DELETE', 'Bulk Delete'), ('BULK_LOCATION', 'Bulk Location Update'), ('BULK_REMOVE', 'Bulk Remove from Inventory'), ('IMAGE_UPLOAD', 'Image Uploaded'), ('IMAGE_DELETE', 'Image Deleted'), ('EXPORT', 'Data Exported'), ('PRINT_LABEL', 'Label Printed'), ('USER_LOGIN', 'User Identified'), ('PAGE_VIEW', 'Page Viewed'), ('SEARCH', 'Search Performed'), ('ERROR', 'Operation Failed')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='SUCCESS', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('affected_count', models.IntegerField(default=1)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='samples_act_timesta_7ea073_idx'), models.Index(fields=['action', '-timestamp'], name='samples_act_action_3405b5_idx'), models.Index(fields=['object_type', 'object_id'], name='samples_act_object__e83caf_idx')],
            },
        ),
    ]
