# Generated by Django 5.1.1 on 2025-09-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0024_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='export_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='first_export_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_export_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
