# Generated by Django 5.1.1 on 2025-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0025_add_export_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='customer',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='opportunity',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
